- name: Install perl
  apt: pkg=perl

- name: Install cpanm
  apt: pkg=cpanminus

- name: Install libgd
  apt: pkg=libgd-dev

- name: Install required perl modules
  cpanm: name={{ item }}
  with_items:
    - CGI
    - CGI::Carp
    - CGI::Fast
    - DBD::SQLite
    - DBI
    - Data::Dumper
    - Error
    - GD
    - HTML::Entities
    - IO::File
    - IO::Pipe
    - Inline
    - Math::MatrixReal
    - POSIX
    - Text::CSV

- name: Install apache
  apt: pkg=apache2

- name: Download tarball of politicalsurvey
  get_url:
    url="http://politics.beasts.org/internals/politicalsurvey.tar.gz"
    dest="/srv"
  register: new_archive

- name: Unarchive source
  unarchive:
    src="/srv/politicalsurvey.tar.gz"
    dest="/srv"
    copy=no
  when: new_archive|changed

- name: Configure apache
  template: src=apache.conf dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache
