- name: Install perl
  apt: pkg=perl

- name: Install cpanm
  apt: pkg=cpanminus

- name: Install libgd
  apt: pkg=libgd-dev

- name: Install required perl modules
  cpanm: name={{ item }}
  with_items:
    - CGI
    - CGI::Carp
    - CGI::Fast
    - DBD::SQLite
    - DBI
    - Data::Dumper
    - Error
    - GD
    - HTML::Entities
    - IO::File
    - IO::Pipe
    - Inline
    - Math::MatrixReal
    - POSIX
    - Text::CSV

- name: Install apache
  apt: pkg=apache2

- name: Download tarball of politicalsurvey
  get_url:
    url="http://politics.beasts.org/internals/politicalsurvey.tar.gz"
    dest="/srv"
  register: new_archive

- name: Unarchive source
  unarchive:
    src="/srv/politicalsurvey.tar.gz"
    dest="/srv"
    copy=no
  when: new_archive|changed

- name: Configure site
  template: src=site.conf dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: Configure apache
  template: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify: restart apache

- name: Enable the apache include module
  apache2_module: state=present name=include
  notify: restart apache

- name: Install fast cgi module for apache
  apt: pkg=libapache2-mod-fcgid
  notify: restart apache

- name: Replace path in source code
  replace: dest=/srv/politicalsurvey/{{ item }} regexp='/path/to/politicalsurvey/' replace='/srv/politicalsurvey/' backup=yes
  with_items:
    - web/scripts/survey
    - web/scripts/statementlist
    - web/scripts/results
    - web/scripts/eigenvectors
    - web/scripts/celebrity
    - lib/PoliticalSurvey.pm
    - scripts/aggregate
    - scripts/allresscatter
    - scripts/eigen
    - scripts/makedatabase
    - scripts/newstatements
    - scripts/ploteigs
    - scripts/publicdump
    - scripts/report
    - scripts/texstatements
